apiVersion: v1
kind: Service
metadata:
  name: tyk-identity-broker
  namespace: tyk
spec:
  ports:
  - port: 3010
    targetPort: 3010
    protocol: TCP
  selector:
    app: tyk-identity-broker
  type: LoadBalancer
